name: My 2nd Workflow
on: push
jobs:
    Script_execute:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: List files
              run: ls -lrta
            - name: Execute script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh