name: Multi Job Exexcution
on: push
jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Install Cowsay
              run: |
                sudo apt-get install cowsay -y
            - name: Execute Command
              run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-test-file
                path: dragon.txt


    Test_job_2:
        needs: Build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v5
              with:
                name: dragon-test-file
                path: dragon.txt

            - name: Test file exists
              run: grep -i dragon dragon.txt
              
    Deploy_job_3:
        needs: Test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v5
              with:
                name: dragon-test-file
                path: dragon.txt            
            - name: Read file
              run: cat dragon.txt
            - name: Deploy
              run: echo   "Deploying ..."   